### PR TITLE
use automaxprocs to calculate the number of CPUs

### PR DESCRIPTION
**Pull request by dprotaso**
this is  useful for container environments

Addresses: https://github.com/google/ko/issues/642

### CODE REVIEW

**Comment by dprotaso** [comment]
Related issue: https://github.com/golang/go/issues/33803

**Comment by dprotaso** [comment]
Essentially GOMAXPROCS is not cgroup aware so it reports the total CPUs on the machine instead of the # of CPUs allocated to the container

**Comment by dprotaso** [comment]
got the typo fixed upstream - force pushing the fix

**Review by imjasonh — APPROVED** [review]
This seems worth doing, and unlikely to cause any new problems. After this is merged I'll try it out and see if it changes the behavior.

Thanks for this fix!

**Comment by akshayjshah** [comment]
Keep in mind that `automaxprocs` doesn't (yet) support cgroups v2 :)

**Pull request merged**
