### PR TITLE
Look for ko.local in the daemon

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
Fixes https://github.com/google/ko/issues/368

### CODE REVIEW

**Comment by imjasonh** [comment]
Can you also add this to the docs? We might want a quick example of building a base image locally then ko-publishing on top of it, and the `ko.local` convention would be useful to spell out.

**Comment by jonjohnsonjr** [comment]
> a quick example of ...

We might want a directory with examples to avoid polluting the README? Would also be nice for getting started. Too lazy to do that for this PR :)

**Review by misterikkit — APPROVED** [review]
Are there other places where a ref to `ko.local` might not resolve to the daemon? Eventually, it would be nice to have a consistent "ko.local means daemon" behavior across all surfaces.

**Comment by jonjohnsonjr** [comment]
I think this covers everything. We pull base images and push built images, and the base image side probably doesn't receive as much love because (usually) the distroless default base is good enough.

**Comment by jonjohnsonjr** [comment]
@imjasonh ptal

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
